name: "v4vendeta's homepage"
description: "personal web site"

url: "https://v4vendetalhy.cn/"
baseurl: ""

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax

# plugins:
# - jekyll-paginate
# paginate: 10
# paginate_path: /page-:num

#disqus-id: your-disqus-id

source: .
destination: ./_site

sass:
  style: :compressed
  sass_dir: assets/css/
